
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAIS = 3;
  public static final int PTVIRG = 6;
  public static final int INTEIRO = 2;
  public static final int MENOSUNARIO = 5;
  public static final int MENOS = 4;
  public static final int EOF = 0;
  public static final int PARENTESQ = 7;
  public static final int error = 1;
  public static final int PARENTDIR = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEIRO",
  "MAIS",
  "MENOS",
  "MENOSUNARIO",
  "PTVIRG",
  "PARENTESQ",
  "PARENTDIR"
  };
}

